/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ViewController;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author esteban
 */
public class CharacterCreator extends javax.swing.JFrame {
    
    private ViewController controller;
    private String noImagePath = "src/images/noImage.jpg";
    
    private JFileChooser openFileChosser;
    private final boolean isLinux = System.getProperty("os.name").contains("Linux") ? true : false;

    /**
     * Creates new form CharacterCreator
     */
    public CharacterCreator() {
        initComponents();
        controller = new ViewController();
        setMinSpinners();
        setLists();
        setImage(noImagePath,characterLabel);
        setImage(noImagePath,weaponLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        characterLabel = new javax.swing.JLabel();
        weaponLabel = new javax.swing.JLabel();
        selectImageWeoponButton = new javax.swing.JButton();
        selectImageCharacterButton = new javax.swing.JButton();
        nameCharacter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameWeapon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        isInventaryButton = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        weaponList = new javax.swing.JList<>();
        directionBox = new javax.swing.JComboBox<>();
        moveSteps = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        damageCharacter = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        levelCharacter = new javax.swing.JSpinner();
        xCharacter = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        yCharacter = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        size = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        maxHealth = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        hitPerUnitTime = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        cost = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        unlockLevel = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        saveCharacter = new javax.swing.JButton();
        saveCharacterPrototype = new javax.swing.JButton();
        newCharacter = new javax.swing.JButton();
        levelWeapon = new javax.swing.JSpinner();
        xWeapon = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        yWeapon = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        damageWeapon = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        scope = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        explosionRange = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        maxSupplies = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        levelMultiplier = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        levelDepend = new javax.swing.JCheckBox();
        saveWeapon = new javax.swing.JButton();
        addWeaponInventary = new javax.swing.JButton();
        newWeapon = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        levelSpriteInput = new javax.swing.JSpinner();
        saveSprite = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        characterList = new javax.swing.JList<>();
        stateSpriteInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        spriteListLevel = new javax.swing.JList<>();
        weaponEquipedButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        spriteListState = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        saveCharacterSoft = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        softCharacterList = new javax.swing.JList<>();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        softWeaponList = new javax.swing.JList<>();
        saveWeaponPrototype = new javax.swing.JButton();
        saveWeaponSoft = new javax.swing.JButton();
        characterSelecterToPrint = new javax.swing.JComboBox<>();
        numberCopiesCharacter = new javax.swing.JSpinner();
        buildCharacter = new javax.swing.JButton();
        weaponSelecterToPrint = new javax.swing.JComboBox<>();
        numberCopiesWeapon = new javax.swing.JSpinner();
        buildWeapon = new javax.swing.JButton();
        levelSpriteWeapon = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        saveSpriteWeapon = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        spriteListWeapon = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creador de personajes");

        characterLabel.setToolTipText("");
        characterLabel.setBorder(new javax.swing.border.MatteBorder(null));
        characterLabel.setMaximumSize(new java.awt.Dimension(250, 250));
        characterLabel.setPreferredSize(new java.awt.Dimension(250, 250));

        weaponLabel.setToolTipText("");
        weaponLabel.setBorder(new javax.swing.border.MatteBorder(null));
        weaponLabel.setMaximumSize(new java.awt.Dimension(250, 250));
        weaponLabel.setPreferredSize(new java.awt.Dimension(250, 250));

        selectImageWeoponButton.setText("Seleccionar imagen");
        selectImageWeoponButton.setMaximumSize(new java.awt.Dimension(250, 24));
        selectImageWeoponButton.setMinimumSize(new java.awt.Dimension(250, 24));
        selectImageWeoponButton.setPreferredSize(new java.awt.Dimension(250, 24));
        selectImageWeoponButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectImageWeoponButtonActionPerformed(evt);
            }
        });

        selectImageCharacterButton.setText("Seleccionar imagen");
        selectImageCharacterButton.setMaximumSize(new java.awt.Dimension(250, 24));
        selectImageCharacterButton.setMinimumSize(new java.awt.Dimension(250, 24));
        selectImageCharacterButton.setPreferredSize(new java.awt.Dimension(250, 24));
        selectImageCharacterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectImageCharacterButtonActionPerformed(evt);
            }
        });

        nameCharacter.setForeground(new java.awt.Color(153, 153, 153));
        nameCharacter.setText("Nombre");
        nameCharacter.setMaximumSize(new java.awt.Dimension(250, 24));
        nameCharacter.setMinimumSize(new java.awt.Dimension(250, 24));
        nameCharacter.setPreferredSize(new java.awt.Dimension(250, 24));
        nameCharacter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameCharacterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameCharacterFocusLost(evt);
            }
        });
        nameCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCharacterActionPerformed(evt);
            }
        });
        nameCharacter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameCharacterKeyTyped(evt);
            }
        });

        jLabel1.setText("Personaje");

        jLabel2.setText("Arma");

        nameWeapon.setForeground(new java.awt.Color(153, 153, 153));
        nameWeapon.setText("Nombre");
        nameWeapon.setMaximumSize(new java.awt.Dimension(250, 24));
        nameWeapon.setMinimumSize(new java.awt.Dimension(250, 24));
        nameWeapon.setPreferredSize(new java.awt.Dimension(250, 24));
        nameWeapon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameWeaponFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameWeaponFocusLost(evt);
            }
        });
        nameWeapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameWeaponActionPerformed(evt);
            }
        });
        nameWeapon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameWeaponKeyTyped(evt);
            }
        });

        jLabel3.setText("Lista de armas en temporales");

        isInventaryButton.setText("Solitarias");
        isInventaryButton.setPreferredSize(new java.awt.Dimension(250, 24));
        isInventaryButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                isInventaryButtonStateChanged(evt);
            }
        });
        isInventaryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isInventaryButtonMouseClicked(evt);
            }
        });
        isInventaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isInventaryButtonActionPerformed(evt);
            }
        });

        weaponList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        weaponList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                weaponListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(weaponList);

        directionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una dirección", "Arriba", "Abajo", "Izquierda", "Derecha" }));
        directionBox.setToolTipText("");
        directionBox.setPreferredSize(new java.awt.Dimension(250, 24));
        directionBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                directionBoxItemStateChanged(evt);
            }
        });
        directionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directionBoxActionPerformed(evt);
            }
        });

        moveSteps.setName("Cantidad de pasos "); // NOI18N
        moveSteps.setPreferredSize(new java.awt.Dimension(250, 24));
        moveSteps.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                moveStepsStateChanged(evt);
            }
        });

        jLabel5.setText("Cantidad de pasos");

        damageCharacter.setName("Cantidad de pasos "); // NOI18N
        damageCharacter.setPreferredSize(new java.awt.Dimension(250, 24));
        damageCharacter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                damageCharacterStateChanged(evt);
            }
        });

        jLabel6.setText("Daño");

        jLabel7.setText("Nivel");

        levelCharacter.setName("Cantidad de pasos "); // NOI18N
        levelCharacter.setPreferredSize(new java.awt.Dimension(250, 24));
        levelCharacter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                levelCharacterStateChanged(evt);
            }
        });

        xCharacter.setName("Cantidad de pasos "); // NOI18N
        xCharacter.setPreferredSize(new java.awt.Dimension(250, 24));
        xCharacter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xCharacterStateChanged(evt);
            }
        });

        jLabel8.setText("Posición en X");

        yCharacter.setName("Cantidad de pasos "); // NOI18N
        yCharacter.setPreferredSize(new java.awt.Dimension(250, 24));
        yCharacter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yCharacterStateChanged(evt);
            }
        });

        jLabel9.setText("Posición en Y");

        size.setName("Cantidad de pasos "); // NOI18N
        size.setPreferredSize(new java.awt.Dimension(250, 24));
        size.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sizeStateChanged(evt);
            }
        });

        jLabel10.setText("Tamaño");

        maxHealth.setName("Cantidad de pasos "); // NOI18N
        maxHealth.setPreferredSize(new java.awt.Dimension(250, 24));
        maxHealth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                maxHealthStateChanged(evt);
            }
        });

        jLabel11.setText("Salud");

        hitPerUnitTime.setName("Cantidad de pasos "); // NOI18N
        hitPerUnitTime.setPreferredSize(new java.awt.Dimension(250, 24));
        hitPerUnitTime.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hitPerUnitTimeStateChanged(evt);
            }
        });

        jLabel13.setText("Golpes por unidad de tiempo");

        cost.setName("Cantidad de pasos "); // NOI18N
        cost.setPreferredSize(new java.awt.Dimension(250, 24));
        cost.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                costStateChanged(evt);
            }
        });

        jLabel14.setText("Costo");

        unlockLevel.setName("Cantidad de pasos "); // NOI18N
        unlockLevel.setPreferredSize(new java.awt.Dimension(250, 24));
        unlockLevel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                unlockLevelStateChanged(evt);
            }
        });

        jLabel15.setText("Nivel de desbloqueo");

        saveCharacter.setText("Guardar Personaje en Prototype");
        saveCharacter.setPreferredSize(new java.awt.Dimension(250, 24));
        saveCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCharacterActionPerformed(evt);
            }
        });

        saveCharacterPrototype.setText("Guardar Prototypes en Json");
        saveCharacterPrototype.setActionCommand("");
        saveCharacterPrototype.setPreferredSize(new java.awt.Dimension(250, 24));
        saveCharacterPrototype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCharacterPrototypeActionPerformed(evt);
            }
        });

        newCharacter.setText("Nuevo Personaje");
        newCharacter.setPreferredSize(new java.awt.Dimension(250, 24));
        newCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCharacterActionPerformed(evt);
            }
        });

        levelWeapon.setName("Cantidad de pasos "); // NOI18N
        levelWeapon.setPreferredSize(new java.awt.Dimension(250, 24));
        levelWeapon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                levelWeaponStateChanged(evt);
            }
        });

        xWeapon.setName("Cantidad de pasos "); // NOI18N
        xWeapon.setPreferredSize(new java.awt.Dimension(250, 24));
        xWeapon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xWeaponStateChanged(evt);
            }
        });

        jLabel16.setText("Posición en X");

        yWeapon.setName("Cantidad de pasos "); // NOI18N
        yWeapon.setPreferredSize(new java.awt.Dimension(250, 24));
        yWeapon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yWeaponStateChanged(evt);
            }
        });

        jLabel17.setText("Posición en Y");

        damageWeapon.setName("Cantidad de pasos "); // NOI18N
        damageWeapon.setPreferredSize(new java.awt.Dimension(250, 24));
        damageWeapon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                damageWeaponStateChanged(evt);
            }
        });

        jLabel18.setText("Daño");

        jLabel19.setText("Nivel");

        scope.setName("Cantidad de pasos "); // NOI18N
        scope.setPreferredSize(new java.awt.Dimension(250, 24));
        scope.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                scopeStateChanged(evt);
            }
        });

        jLabel20.setText("Alcance");

        explosionRange.setName("Cantidad de pasos "); // NOI18N
        explosionRange.setPreferredSize(new java.awt.Dimension(250, 24));
        explosionRange.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                explosionRangeStateChanged(evt);
            }
        });

        jLabel21.setText("Rango de explosión");

        maxSupplies.setName("Cantidad de pasos "); // NOI18N
        maxSupplies.setPreferredSize(new java.awt.Dimension(250, 24));
        maxSupplies.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                maxSuppliesStateChanged(evt);
            }
        });

        jLabel22.setText("Munición");

        levelMultiplier.setName("Cantidad de pasos "); // NOI18N
        levelMultiplier.setPreferredSize(new java.awt.Dimension(250, 24));
        levelMultiplier.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                levelMultiplierStateChanged(evt);
            }
        });

        jLabel24.setText("Multiplicador de nivel");

        jLabel25.setText("Nivel ");

        levelDepend.setText("Dependiente");
        levelDepend.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                levelDependStateChanged(evt);
            }
        });
        levelDepend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelDependActionPerformed(evt);
            }
        });

        saveWeapon.setText("Guardar Arma en Prototype");
        saveWeapon.setPreferredSize(new java.awt.Dimension(250, 24));
        saveWeapon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveWeaponMouseClicked(evt);
            }
        });
        saveWeapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveWeaponActionPerformed(evt);
            }
        });

        addWeaponInventary.setText("Agregar a inventario");
        addWeaponInventary.setPreferredSize(new java.awt.Dimension(250, 24));
        addWeaponInventary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWeaponInventaryActionPerformed(evt);
            }
        });

        newWeapon.setText("Nuevo Arma");
        newWeapon.setActionCommand("Nueva Arma");
        newWeapon.setPreferredSize(new java.awt.Dimension(250, 24));
        newWeapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWeaponActionPerformed(evt);
            }
        });

        jLabel26.setText("Nivel");

        levelSpriteInput.setName("Cantidad de pasos "); // NOI18N
        levelSpriteInput.setPreferredSize(new java.awt.Dimension(250, 24));

        saveSprite.setText("Guardar Sprite");
        saveSprite.setPreferredSize(new java.awt.Dimension(250, 24));
        saveSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSpriteActionPerformed(evt);
            }
        });

        jLabel27.setText("Lista de personajes temporales");

        characterList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        characterList.setPreferredSize(new java.awt.Dimension(250, 100));
        characterList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                characterListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(characterList);

        stateSpriteInput.setForeground(new java.awt.Color(153, 153, 153));
        stateSpriteInput.setText("Estado");
        stateSpriteInput.setMaximumSize(new java.awt.Dimension(250, 24));
        stateSpriteInput.setMinimumSize(new java.awt.Dimension(250, 24));
        stateSpriteInput.setPreferredSize(new java.awt.Dimension(250, 24));
        stateSpriteInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stateSpriteInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stateSpriteInputFocusLost(evt);
            }
        });
        stateSpriteInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateSpriteInputActionPerformed(evt);
            }
        });

        spriteListLevel.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spriteListLevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spriteListLevelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(spriteListLevel);

        weaponEquipedButton.setText("Selecciona un arma a equipar");
        weaponEquipedButton.setPreferredSize(new java.awt.Dimension(250, 24));
        weaponEquipedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weaponEquipedButtonActionPerformed(evt);
            }
        });

        spriteListState.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spriteListState.setPreferredSize(new java.awt.Dimension(250, 100));
        spriteListState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spriteListStateMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(spriteListState);

        jLabel4.setText("Por estado");

        jLabel28.setText("Por nivel");

        saveCharacterSoft.setText("Guardar Personaje Temporal");
        saveCharacterSoft.setPreferredSize(new java.awt.Dimension(250, 24));
        saveCharacterSoft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCharacterSoftActionPerformed(evt);
            }
        });

        jLabel29.setText("Lista de personajes en prototype");

        softCharacterList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        softCharacterList.setPreferredSize(new java.awt.Dimension(250, 100));
        softCharacterList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                softCharacterListMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(softCharacterList);

        jLabel30.setText("Lista de armas en Prototype");

        softWeaponList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        softWeaponList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                softWeaponListMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(softWeaponList);

        saveWeaponPrototype.setText("Guardar Prototypes en Json");
        saveWeaponPrototype.setPreferredSize(new java.awt.Dimension(250, 24));
        saveWeaponPrototype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveWeaponPrototypeMouseClicked(evt);
            }
        });
        saveWeaponPrototype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveWeaponPrototypeActionPerformed(evt);
            }
        });

        saveWeaponSoft.setText("Guardar Arma Temporal");
        saveWeaponSoft.setPreferredSize(new java.awt.Dimension(250, 24));
        saveWeaponSoft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveWeaponSoftMouseClicked(evt);
            }
        });
        saveWeaponSoft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveWeaponSoftActionPerformed(evt);
            }
        });

        characterSelecterToPrint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un personaje" }));
        characterSelecterToPrint.setToolTipText("");
        characterSelecterToPrint.setPreferredSize(new java.awt.Dimension(250, 24));
        characterSelecterToPrint.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                characterSelecterToPrintItemStateChanged(evt);
            }
        });
        characterSelecterToPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterSelecterToPrintActionPerformed(evt);
            }
        });

        numberCopiesCharacter.setToolTipText("");
        numberCopiesCharacter.setName("Cantidad de pasos "); // NOI18N
        numberCopiesCharacter.setPreferredSize(new java.awt.Dimension(250, 24));
        numberCopiesCharacter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numberCopiesCharacterStateChanged(evt);
            }
        });

        buildCharacter.setText("Generar");
        buildCharacter.setPreferredSize(new java.awt.Dimension(250, 24));
        buildCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildCharacterActionPerformed(evt);
            }
        });

        weaponSelecterToPrint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un arma" }));
        weaponSelecterToPrint.setToolTipText("");
        weaponSelecterToPrint.setPreferredSize(new java.awt.Dimension(250, 24));
        weaponSelecterToPrint.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                weaponSelecterToPrintItemStateChanged(evt);
            }
        });
        weaponSelecterToPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weaponSelecterToPrintActionPerformed(evt);
            }
        });

        numberCopiesWeapon.setName("Cantidad de pasos "); // NOI18N
        numberCopiesWeapon.setPreferredSize(new java.awt.Dimension(250, 24));
        numberCopiesWeapon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numberCopiesWeaponStateChanged(evt);
            }
        });

        buildWeapon.setText("Generar");
        buildWeapon.setPreferredSize(new java.awt.Dimension(250, 24));
        buildWeapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildWeaponActionPerformed(evt);
            }
        });

        levelSpriteWeapon.setName("Cantidad de pasos "); // NOI18N
        levelSpriteWeapon.setPreferredSize(new java.awt.Dimension(250, 24));

        jLabel31.setText("Nivel");

        saveSpriteWeapon.setText("Guardar Sprite");
        saveSpriteWeapon.setPreferredSize(new java.awt.Dimension(250, 24));
        saveSpriteWeapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSpriteWeaponActionPerformed(evt);
            }
        });

        spriteListWeapon.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spriteListWeapon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spriteListWeaponMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(spriteListWeapon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(characterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectImageCharacterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(levelSpriteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stateSpriteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nameCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(damageCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(levelCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(xCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(yCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(maxHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(nameWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(damageWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(levelWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(xWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(yWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(scope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(explosionRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weaponLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectImageWeoponButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(levelSpriteWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveSpriteWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hitPerUnitTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(unlockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxSupplies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(levelMultiplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(5, 5, 5)
                        .addComponent(levelDepend))
                    .addComponent(saveWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(moveSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(directionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weaponEquipedButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveCharacterPrototype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveCharacterSoft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(characterSelecterToPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberCopiesCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buildCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveWeaponPrototype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveWeaponSoft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addWeaponInventary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weaponSelecterToPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberCopiesWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buildWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isInventaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(characterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(selectImageCharacterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel31)
                        .addGap(2, 2, 2)
                        .addComponent(levelSpriteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(stateSpriteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(nameCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(damageCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(levelCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)
                        .addGap(2, 2, 2)
                        .addComponent(xCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9)
                        .addGap(2, 2, 2)
                        .addComponent(yCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10)
                        .addGap(2, 2, 2)
                        .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11)
                        .addGap(2, 2, 2)
                        .addComponent(maxHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2)
                        .addComponent(nameWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel18)
                        .addGap(2, 2, 2)
                        .addComponent(damageWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel19)
                        .addGap(2, 2, 2)
                        .addComponent(levelWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel16)
                        .addGap(2, 2, 2)
                        .addComponent(xWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17)
                        .addGap(2, 2, 2)
                        .addComponent(yWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel20)
                        .addGap(2, 2, 2)
                        .addComponent(scope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel21)
                        .addGap(2, 2, 2)
                        .addComponent(explosionRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weaponLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(selectImageWeoponButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel26)
                        .addGap(2, 2, 2)
                        .addComponent(levelSpriteWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(saveSpriteWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel28)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hitPerUnitTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14)
                        .addGap(2, 2, 2)
                        .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15)
                        .addGap(2, 2, 2)
                        .addComponent(unlockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(maxSupplies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel24)
                        .addGap(2, 2, 2)
                        .addComponent(levelMultiplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(levelDepend)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(saveWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel29)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel27)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(moveSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(directionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(weaponEquipedButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(saveCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(saveCharacterPrototype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(saveCharacterSoft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(newCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(characterSelecterToPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(numberCopiesCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(buildCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveWeaponPrototype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(saveWeaponSoft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(newWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(addWeaponInventary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(weaponSelecterToPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(numberCopiesWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(buildWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(isInventaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel30)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectImageCharacterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectImageCharacterButtonActionPerformed
       String path = getSelectedPath();
       path = path.substring(path.indexOf("src"));
       if(path != null){
           setImage(path,characterLabel);
           controller.setPath(path);
       } else {
           System.out.println("No seleccionó ningún archivo");
       }
    }//GEN-LAST:event_selectImageCharacterButtonActionPerformed

    private void selectImageWeoponButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectImageWeoponButtonActionPerformed
       String path = getSelectedPath();
       if(path != null){
           controller.setPath(path);
           setImage(path,weaponLabel);
       } else {
           System.out.println("No seleccionó ningún archivo");
       }
    }//GEN-LAST:event_selectImageWeoponButtonActionPerformed

    private void nameCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameCharacterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameCharacterActionPerformed

    private void nameCharacterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameCharacterFocusGained
        if(nameCharacter.getText().equals("Nombre")){
            nameCharacter.setText("");
            nameCharacter.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_nameCharacterFocusGained

    private void nameCharacterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameCharacterFocusLost
        if(nameCharacter.getText().equals("")){
            nameCharacter.setText("Nombre");
            nameCharacter.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_nameCharacterFocusLost

    private void nameWeaponFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameWeaponFocusGained
        if(nameWeapon.getText().equals("Nombre")){
            nameWeapon.setText("");
            nameWeapon.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_nameWeaponFocusGained

    private void nameWeaponFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameWeaponFocusLost
        if(nameWeapon.getText().equals("")){
            nameWeapon.setText("Nombre");
            nameWeapon.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_nameWeaponFocusLost

    private void nameWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameWeaponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameWeaponActionPerformed

    private void isInventaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isInventaryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isInventaryButtonActionPerformed

    private void levelDependActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelDependActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelDependActionPerformed

    private void saveSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSpriteActionPerformed
        controller.addStripteSet((int) levelSpriteInput.getValue(),
                stateSpriteInput.getText());
        setListSpriteLevel();
    }//GEN-LAST:event_saveSpriteActionPerformed

    private void stateSpriteInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateSpriteInputFocusGained
        if(stateSpriteInput.getText().equals("Estado")){
            stateSpriteInput.setText("");
            stateSpriteInput.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_stateSpriteInputFocusGained

    private void stateSpriteInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateSpriteInputFocusLost
        if(stateSpriteInput.getText().equals("")){
            stateSpriteInput.setText("Estado");
            stateSpriteInput.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_stateSpriteInputFocusLost

    private void stateSpriteInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateSpriteInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateSpriteInputActionPerformed

    private void characterListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_characterListMouseClicked
        int indexCharacter = characterList.locationToIndex(evt.getPoint());
        controller.setCharacter(indexCharacter);
        setCharacterUI();
    }//GEN-LAST:event_characterListMouseClicked

    private void weaponListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weaponListMouseClicked
        int indexWeapon = weaponList.locationToIndex(evt.getPoint());
        if(controller.anyWeapon(isInventaryButton.isSelected())){
            controller.setWeapon(indexWeapon,isInventaryButton.isSelected());
            setWeaponUI();
        } else {
            showMessageDialog(null, "No hay armas");
        }
        
    }//GEN-LAST:event_weaponListMouseClicked

    private void damageCharacterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_damageCharacterStateChanged
        controller.setDamage((int) damageCharacter.getValue(),true);
    }//GEN-LAST:event_damageCharacterStateChanged

    private void damageWeaponStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_damageWeaponStateChanged
        controller.setDamage((int) damageWeapon.getValue(),false);
    }//GEN-LAST:event_damageWeaponStateChanged

    private void levelCharacterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_levelCharacterStateChanged
        controller.setLevel((int) levelCharacter.getValue(),true);
    }//GEN-LAST:event_levelCharacterStateChanged

    private void levelWeaponStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_levelWeaponStateChanged
        controller.setLevel((int) levelWeapon.getValue(),false);
    }//GEN-LAST:event_levelWeaponStateChanged

    private void xCharacterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_xCharacterStateChanged
        controller.setX((int) xCharacter.getValue(), true);
    }//GEN-LAST:event_xCharacterStateChanged

    private void levelDependStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_levelDependStateChanged
        controller.setLevelDependant(levelDepend.isSelected());
    }//GEN-LAST:event_levelDependStateChanged

    private void xWeaponStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_xWeaponStateChanged
        controller.setX((int) xCharacter.getValue(), false);
    }//GEN-LAST:event_xWeaponStateChanged

    private void yCharacterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yCharacterStateChanged
        controller.setY((int) xCharacter.getValue(), true);
    }//GEN-LAST:event_yCharacterStateChanged

    private void yWeaponStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yWeaponStateChanged
        controller.setY((int) xCharacter.getValue(), false);
    }//GEN-LAST:event_yWeaponStateChanged

    private void sizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sizeStateChanged
        controller.setSize((int) size.getValue());
    }//GEN-LAST:event_sizeStateChanged

    private void maxHealthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maxHealthStateChanged
        controller.setMaxHealth((int) maxHealth.getValue());
    }//GEN-LAST:event_maxHealthStateChanged

    private void hitPerUnitTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hitPerUnitTimeStateChanged
        controller.setHitsPerTimeUnit((int) hitPerUnitTime.getValue());
    }//GEN-LAST:event_hitPerUnitTimeStateChanged

    private void costStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_costStateChanged
        controller.setCost((int) cost.getValue());
    }//GEN-LAST:event_costStateChanged

    private void unlockLevelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_unlockLevelStateChanged
        controller.setUnlockLevel((int) unlockLevel.getValue());
    }//GEN-LAST:event_unlockLevelStateChanged

    private void moveStepsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_moveStepsStateChanged
        controller.setMoveSteps((int) moveSteps.getValue());
    }//GEN-LAST:event_moveStepsStateChanged

    private void scopeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_scopeStateChanged
        controller.setScope((int) scope.getValue());
    }//GEN-LAST:event_scopeStateChanged

    private void explosionRangeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_explosionRangeStateChanged
        controller.setExplosionRange((int) explosionRange.getValue());
    }//GEN-LAST:event_explosionRangeStateChanged

    private void maxSuppliesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maxSuppliesStateChanged
        controller.setMaxSupplies((int) maxSupplies.getValue());
    }//GEN-LAST:event_maxSuppliesStateChanged

    private void levelMultiplierStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_levelMultiplierStateChanged
        controller.setLevelMultiplier((int) levelMultiplier.getValue());
    }//GEN-LAST:event_levelMultiplierStateChanged

    private void nameCharacterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameCharacterKeyTyped
        controller.setName(nameCharacter.getText(),true);
    }//GEN-LAST:event_nameCharacterKeyTyped

    private void nameWeaponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameWeaponKeyTyped
        controller.setName(nameWeapon.getText(),false);
    }//GEN-LAST:event_nameWeaponKeyTyped

    private void weaponEquipedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponEquipedButtonActionPerformed
        String[] options = controller.getNameWeapons();
        if(options[0].contains("No hay armas aún")){
            showMessageDialog(null, options[0]);
        } else {
           ImageIcon icon = new ImageIcon("src/images/icon.png");
           String name = (String)JOptionPane.showInputDialog(null, "Selecciona el arma que quieras", 
                "Selecciona un arma", JOptionPane.QUESTION_MESSAGE,icon, options, options[0]);
           if(name != null){
               controller.setEquipedWeapon(Arrays.asList(options).indexOf(name));
               if(controller.getDataCharacter().getEquipedWeapon() != null){
                    weaponEquipedButton.setText("Arma equipada:" + controller
                            .getDataCharacter().getEquipedWeapon().getName());
               }
           }
           
        }
    }//GEN-LAST:event_weaponEquipedButtonActionPerformed

    private void saveCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCharacterActionPerformed
        boolean isSaved = controller.save(true,false,nameCharacter.getText());
        setLists();
        if(isSaved){
            clearCharacterView();
            showMessageDialog(null,"Prototipos de personaje actualizados");
        }
    }//GEN-LAST:event_saveCharacterActionPerformed

    private void saveWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveWeaponActionPerformed
        boolean isSaved = controller.save(false, isInventaryButton.isSelected(),nameWeapon.getText());
        setLists();
        if(isSaved){
            clearWeaponView();
            showMessageDialog(null,"Armas Prototype actualizadas");
        }
    }//GEN-LAST:event_saveWeaponActionPerformed

    private void saveCharacterPrototypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCharacterPrototypeActionPerformed
        controller.savePrototype(true);
        showMessageDialog(null,"Personajes Prototype guardados en json exitosamente");
        newCharacterActionPerformed(evt); 
    }//GEN-LAST:event_saveCharacterPrototypeActionPerformed

    private void addWeaponInventaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWeaponInventaryActionPerformed
        controller.addWeaponInventory();
        showMessageDialog(null,"Arma agregada al inventario");
        clearWeaponView();
        if(isInventaryButton.isSelected()){
            setListWeapon(isInventaryButton.isSelected());
        }
    }//GEN-LAST:event_addWeaponInventaryActionPerformed

    private void newCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCharacterActionPerformed
        controller.newGameObject(true);
        clearCharacterView();
        setListStriteState(-1);
        setListSpriteLevel();
    }//GEN-LAST:event_newCharacterActionPerformed

    private void newWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWeaponActionPerformed
        controller.newGameObject(false);
        clearWeaponView();
    }//GEN-LAST:event_newWeaponActionPerformed

    private void isInventaryButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_isInventaryButtonStateChanged
        
    }//GEN-LAST:event_isInventaryButtonStateChanged

    private void isInventaryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isInventaryButtonMouseClicked
        if(isInventaryButton.isSelected()){
            isInventaryButton.setText("Inventario");
        } else {
            isInventaryButton.setText("Solitarias");
        }
        clearWeaponView();
        setListWeapon(isInventaryButton.isSelected());
    }//GEN-LAST:event_isInventaryButtonMouseClicked

    private void saveWeaponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveWeaponMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_saveWeaponMouseClicked

    private void spriteListLevelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spriteListLevelMouseClicked
        int indexLevel = spriteListLevel.locationToIndex(evt.getPoint());
        if(controller.anySpriteSet()){
            int level = controller.getLevelSprite(indexLevel);
            setListStriteState(level);
        } else {
           showMessageDialog(null, "No hay sprit sets"); 
        }
    }//GEN-LAST:event_spriteListLevelMouseClicked

    private void directionBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_directionBoxItemStateChanged
        controller.setDirection(directionBox.getSelectedItem().toString());
    }//GEN-LAST:event_directionBoxItemStateChanged

    private void directionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directionBoxActionPerformed

    private void saveCharacterSoftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCharacterSoftActionPerformed
        controller.saveSoftCharacter();
        clearCharacterView();
        setListSoftCharacter();
        showMessageDialog(null,"Personaje temporal guardado");
    }//GEN-LAST:event_saveCharacterSoftActionPerformed

    private void softCharacterListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_softCharacterListMouseClicked
        if(controller.anySoft(true)){
            int index = softCharacterList.locationToIndex(evt.getPoint());
            controller.setSoftCharacter(index);
            setCharacterUI();
        } else {
            showMessageDialog(null,"No hay armas temporales");
        }
    }//GEN-LAST:event_softCharacterListMouseClicked

    private void softWeaponListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_softWeaponListMouseClicked
        if(controller.anySoft(false)){
            int index = softWeaponList.locationToIndex(evt.getPoint());
            controller.setSoftWeapon(index);
            setWeaponUI();
        } else {
            showMessageDialog(null,"No hay armas temporales");
        }
    }//GEN-LAST:event_softWeaponListMouseClicked

    private void saveWeaponPrototypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveWeaponPrototypeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_saveWeaponPrototypeMouseClicked

    private void saveWeaponPrototypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveWeaponPrototypeActionPerformed
        controller.savePrototype(false);
        newWeaponActionPerformed(evt); 
        showMessageDialog(null,"Armas Prototype guardadas en json exitosamente");
    }//GEN-LAST:event_saveWeaponPrototypeActionPerformed

    private void saveWeaponSoftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveWeaponSoftMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_saveWeaponSoftMouseClicked

    private void saveWeaponSoftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveWeaponSoftActionPerformed
        controller.saveSoftWeapon();
        clearWeaponView();
        showMessageDialog(null,"Arma temporal guardada");
    }//GEN-LAST:event_saveWeaponSoftActionPerformed

    private void characterSelecterToPrintItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_characterSelecterToPrintItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_characterSelecterToPrintItemStateChanged

    private void characterSelecterToPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterSelecterToPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_characterSelecterToPrintActionPerformed

    private void numberCopiesCharacterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numberCopiesCharacterStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_numberCopiesCharacterStateChanged

    private void buildCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildCharacterActionPerformed
        int amount = (int) numberCopiesCharacter.getValue();
        String name = characterSelecterToPrint.getSelectedItem().toString();
        showMessageDialog(null, controller.getBuildCharacter(name,amount)); 
    }//GEN-LAST:event_buildCharacterActionPerformed

    private void weaponSelecterToPrintItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_weaponSelecterToPrintItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_weaponSelecterToPrintItemStateChanged

    private void weaponSelecterToPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponSelecterToPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weaponSelecterToPrintActionPerformed

    private void numberCopiesWeaponStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numberCopiesWeaponStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_numberCopiesWeaponStateChanged

    private void buildWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildWeaponActionPerformed
        int amount = (int) numberCopiesWeapon.getValue();
        String name = weaponSelecterToPrint.getSelectedItem().toString();
        showMessageDialog(null, controller.getBuildWeapon(name,amount));  
    }//GEN-LAST:event_buildWeaponActionPerformed

    private void saveSpriteWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSpriteWeaponActionPerformed
        controller.addSpriteWeapon((int) levelSpriteWeapon.getValue());
        setListSpriteWeapon();
    }//GEN-LAST:event_saveSpriteWeaponActionPerformed

    private void spriteListWeaponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spriteListWeaponMouseClicked
        int index = spriteListWeapon.locationToIndex(evt.getPoint());
        setImage(controller.getWeaponSpritePath(index),weaponLabel);
        controller.setPath(controller.getWeaponSpritePath(index));
    }//GEN-LAST:event_spriteListWeaponMouseClicked

    private void spriteListStateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spriteListStateMouseClicked
        int index = spriteListState.locationToIndex(evt.getPoint());
        setImage(controller.getCharacterSpritePath(index),characterLabel);
        controller.setPath(controller.getCharacterSpritePath(index));
    }//GEN-LAST:event_spriteListStateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterCreator().setVisible(true);
            }
        });
    }
    
    /**
     * Agregar una imagen a un label
     * @param path la dirección de la imagen
     * @param label el label donde agregar la imagen
     */
    private void setImage(String path,javax.swing.JLabel label) {
        BufferedImage img = null;
        try {
            if(isLinux){
                path = path.replace("\\\\", "/").replace("\\", "/");
            } else {
                path = path.replace("/","\\\\");
            }
            img = ImageIO.read(new File(path));
            Image dimg = img.getScaledInstance(label.getWidth(), 
                    label.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(dimg);
            label.setIcon(imageIcon);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private String getSelectedPath(){
        openFileChosser = new JFileChooser();
        openFileChosser.setCurrentDirectory(new File("src/images/"));
        int returnValue = openFileChosser.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            return openFileChosser.getSelectedFile().getPath();
        } else {
            return null;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addWeaponInventary;
    private javax.swing.JButton buildCharacter;
    private javax.swing.JButton buildWeapon;
    private javax.swing.JLabel characterLabel;
    private javax.swing.JList<String> characterList;
    private javax.swing.JComboBox<String> characterSelecterToPrint;
    private javax.swing.JSpinner cost;
    private javax.swing.JSpinner damageCharacter;
    private javax.swing.JSpinner damageWeapon;
    private javax.swing.JComboBox<String> directionBox;
    private javax.swing.JSpinner explosionRange;
    private javax.swing.JSpinner hitPerUnitTime;
    private javax.swing.JToggleButton isInventaryButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSpinner levelCharacter;
    private javax.swing.JCheckBox levelDepend;
    private javax.swing.JSpinner levelMultiplier;
    private javax.swing.JSpinner levelSpriteInput;
    private javax.swing.JSpinner levelSpriteWeapon;
    private javax.swing.JSpinner levelWeapon;
    private javax.swing.JSpinner maxHealth;
    private javax.swing.JSpinner maxSupplies;
    private javax.swing.JSpinner moveSteps;
    private javax.swing.JTextField nameCharacter;
    private javax.swing.JTextField nameWeapon;
    private javax.swing.JButton newCharacter;
    private javax.swing.JButton newWeapon;
    private javax.swing.JSpinner numberCopiesCharacter;
    private javax.swing.JSpinner numberCopiesWeapon;
    private javax.swing.JButton saveCharacter;
    private javax.swing.JButton saveCharacterPrototype;
    private javax.swing.JButton saveCharacterSoft;
    private javax.swing.JButton saveSprite;
    private javax.swing.JButton saveSpriteWeapon;
    private javax.swing.JButton saveWeapon;
    private javax.swing.JButton saveWeaponPrototype;
    private javax.swing.JButton saveWeaponSoft;
    private javax.swing.JSpinner scope;
    private javax.swing.JButton selectImageCharacterButton;
    private javax.swing.JButton selectImageWeoponButton;
    private javax.swing.JSpinner size;
    private javax.swing.JList<String> softCharacterList;
    private javax.swing.JList<String> softWeaponList;
    private javax.swing.JList<String> spriteListLevel;
    private javax.swing.JList<String> spriteListState;
    private javax.swing.JList<String> spriteListWeapon;
    private javax.swing.JTextField stateSpriteInput;
    private javax.swing.JSpinner unlockLevel;
    private javax.swing.JButton weaponEquipedButton;
    private javax.swing.JLabel weaponLabel;
    private javax.swing.JList<String> weaponList;
    private javax.swing.JComboBox<String> weaponSelecterToPrint;
    private javax.swing.JSpinner xCharacter;
    private javax.swing.JSpinner xWeapon;
    private javax.swing.JSpinner yCharacter;
    private javax.swing.JSpinner yWeapon;
    // End of variables declaration//GEN-END:variables

    private void setLists() {
        setListCharacter();
        setListWeapon(isInventaryButton.isSelected());
        setListSoftCharacter();
        setListSoftWeapons();
        setListSpriteLevel();
        setListStriteState(-1);
        setListSpriteWeapon();
    }
    
    private void setListSpriteWeapon() {
        spriteListWeapon.setModel(controller.getListModelSpriteWeapon());
    }
    
    private void setListStriteState(int level){
        spriteListState.setModel(controller.getListModelSpritesetStates(level));
    }
    
    private void setListSpriteLevel(){
        spriteListLevel.setModel(controller.getListModelSpritsetLevels());
    }
    
    private void setListCharacter(){
        characterList.setModel(controller.getListModelCharacters());
        characterSelecterToPrint.setModel(controller.getListComboModelCharacters());
    }
    
    private void setListWeapon(boolean isInventary) {
        weaponList.setModel(controller.getListModelWeapons(isInventary));
        weaponSelecterToPrint.setModel(controller.getListComboModelWeapons());
    }
    
    private void setListSoftCharacter() {
        softCharacterList.setModel(controller.getListModelSoftCharacters());
    }
        private void setListSoftWeapons() {
        softWeaponList.setModel(controller.getListModelSoftWeapons());
    }
    
    private void clearWeaponView(){
        nameWeapon.setText("Nombre");
        nameWeapon.setForeground(Color.GRAY);
        damageWeapon.setValue(0);
        levelWeapon.setValue(0);
        xWeapon.setValue(0);
        yWeapon.setValue(0);
        scope.setValue(0);
        explosionRange.setValue(0);
        maxSupplies.setValue(0);
        levelMultiplier.setValue(0);
        levelDepend.setSelected(false);
        setImage("./src/images/noImage.jpg",weaponLabel);
        setListSpriteWeapon();
        setListWeapon(isInventaryButton.isSelected());
        setListSoftWeapons();
    }


    private void clearCharacterView() {
       nameCharacter.setText("Nombre");
       nameCharacter.setForeground(Color.GRAY);
       damageCharacter.setValue(0);
       levelCharacter.setValue(0);
       xCharacter.setValue(0);
       yCharacter.setValue(0);
       size.setValue(0);
       maxHealth.setValue(0);
       hitPerUnitTime.setValue(0);
       cost.setValue(0);
       unlockLevel.setValue(0);
       weaponEquipedButton.setText("Selecciona un arma");
       moveSteps.setValue(0);
       directionBox.setSelectedIndex(0);
       setImage(noImagePath,characterLabel);
    }

    private void setMinSpinners() {
        SpinnerNumberModel oneOrMore = new SpinnerNumberModel(1,1,Integer.MAX_VALUE,1);
        // n<=0
        levelCharacter.setModel(new SpinnerNumberModel(0,0,Integer.MAX_VALUE,1));
        levelWeapon.setModel(new SpinnerNumberModel(0,0,Integer.MAX_VALUE,1));
        size.setModel(new SpinnerNumberModel(0,0,Integer.MAX_VALUE,1));
        unlockLevel.setModel(new SpinnerNumberModel(0,0,Integer.MAX_VALUE,1));
        maxHealth.setModel(new SpinnerNumberModel(0,0,Integer.MAX_VALUE,1));
        hitPerUnitTime.setModel(new SpinnerNumberModel(0,0,Integer.MAX_VALUE,1));
        moveSteps.setModel(new SpinnerNumberModel(0,0,Integer.MAX_VALUE,1));
        scope.setModel(new SpinnerNumberModel(0,0,Integer.MAX_VALUE,1));
        levelMultiplier.setModel(new SpinnerNumberModel(0,0,Integer.MAX_VALUE,1));
        maxSupplies.setModel(new SpinnerNumberModel(0,0,Integer.MAX_VALUE,1));
        levelSpriteInput.setModel(new SpinnerNumberModel(0,0,Integer.MAX_VALUE,1));
        levelSpriteWeapon.setModel(new SpinnerNumberModel(0,0,Integer.MAX_VALUE,1));
        // n <= 1
        numberCopiesCharacter.setModel(new SpinnerNumberModel(1,1,Integer.MAX_VALUE,1));
        numberCopiesWeapon.setModel(new SpinnerNumberModel(1,1,Integer.MAX_VALUE,1));
        scope.setModel(new SpinnerNumberModel(1,1,Integer.MAX_VALUE,1));
        explosionRange.setModel(new SpinnerNumberModel(1,1,Integer.MAX_VALUE,1));
        
    }

    private void setWeaponUI() {
        nameWeapon.setText(controller.getDataWeapon().getName());
        nameWeapon.setForeground(Color.BLACK);
        damageWeapon.setValue(controller.getDataWeapon().getRealDamage());
        levelWeapon.setValue(controller.getDataWeapon().getLevel());
        xWeapon.setValue(controller.getDataWeapon().getX());
        yWeapon.setValue(controller.getDataWeapon().getY());
        scope.setValue(controller.getDataWeapon().getScope());
        explosionRange.setValue(controller.getDataWeapon().getExplosionRange());
        maxSupplies.setValue(controller.getDataWeapon().getMaxSupplies());
        levelMultiplier.setValue(controller.getDataWeapon().getLevelMultiplier());
        levelDepend.setSelected(controller.getDataWeapon().isLevelDependant());
        if(controller.getDataWeapon().getSprite() != null){
            setImage(controller.getDataWeapon().getSprite(), weaponLabel);
        } else {
            setImage(noImagePath,weaponLabel);
        }
        setListSpriteWeapon();
    }

    private void setCharacterUI() {
        nameCharacter.setText(controller.getDataCharacter().getName());
        nameCharacter.setForeground(Color.BLACK);
        damageWeapon.setValue(controller.getDataCharacter().getDamage());
        levelCharacter.setValue(controller.getDataCharacter().getLevel());
        xCharacter.setValue(controller.getDataCharacter().getX());
        yCharacter.setValue(controller.getDataCharacter().getY());
        size.setValue(controller.getDataCharacter().getSize());
        maxHealth.setValue(controller.getDataCharacter().getMaxHealth());
        hitPerUnitTime.setValue(controller.getDataCharacter().getHitsPerTimeUnit());
        cost.setValue(controller.getDataCharacter().getCost());
        unlockLevel.setValue(controller.getDataCharacter().getUnlockLevel());
        if(controller.getDataCharacter().getEquipedWeapon() != null){
            weaponEquipedButton.setText("Arma equipada:"
                + controller.getDataCharacter().getEquipedWeapon().getName());
        }
        moveSteps.setValue(controller.getDataCharacter().getMoveSteps());
        if(controller.getDataCharacter().getDirection() != null){
            switch(controller.getDataCharacter().getDirection()){
                case UP:
                    directionBox.setSelectedIndex(1);
                    break;
                case DOWN:
                    directionBox.setSelectedIndex(2);
                    break;
                case LEFT:
                    directionBox.setSelectedIndex(3);
                    break;
                case RIGHT:
                    directionBox.setSelectedIndex(4);
                    break;
            }
        }
        setListSpriteLevel();
        setListStriteState(-1);
    }

}
